name: dart_validator
description: A powerful yet elegant validation library for Dart and Flutter, inspired by Laravel's validator syntax and philosophy.
version: 1.0.0
homepage: https://github.com/MayR-Labs/dart_validator
repository: https://github.com/MayR-Labs/dart_validator
issue_tracker: https://github.com/MayR-Labs/dart_validator/issues
documentation: https://github.com/MayR-Labs/dart_validator/wiki
LICENSE: MIT

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

topics:
  - validation
  - validators
  - dart
  - productivity
  - forms
